- name: Check if OS is supported
  assert:
    that:
      - "ansible_distribution in openvpn_supported_os"
      - "ansible_lsb.get('ansible_distribution_major_version') | default(ansible_distribution_major_version, true) in openvpn_supported_os[ansible_distribution]"
    msg: "{{ ansible_distribution }} (version {{ ansible_lsb.get('ansible_distribution_major_version') | default(ansible_distribution_major_version, true) }})  is not supported"
    success_msg: "{{ ansible_distribution }} {{ ansible_lsb.get('ansible_distribution_major_version') | default(ansible_distribution_major_version, true) }} is supported"