---
- name: Generate client configurations
  template:
    src: "{{ openvpn_client_conf_template }}"
    dest: "{{ openvpn_etcdir }}/ovpns/{{ item }}.ovpn"
  loop: "{{ openvpn_download_clients }}"
  register: openvpn_clients_changed

- name: Pack clients
  command: >-
    zip -j
      {{ item }}.zip
      {{ openvpn_crt_dir }}/issued/{{ item }}.crt
      {{ openvpn_key_dir }}/private/{{ item }}.key
      {{ item }}.ovpn
      {{ openvpn_ca_crt_path }}
#      {{ openvpn_tls_key if openvpn_tls_auth else '' }}
  loop: "{{ openvpn_download_clients }}"
  loop_control:
    index_var: index
  args:
    chdir: "{{ openvpn_etcdir }}/ovpns/"
  when: openvpn_clients_changed.results[index] is changed

- name: Download client credentials
  fetch:
    src: "{{ openvpn_etcdir }}/ovpns/{{ item }}.zip"
    dest: "{{ openvpn_download_dir }}"
    flat: true
    validate_checksum: true
  loop: "{{ openvpn_download_clients }}"
  loop_control:
    index_var: index
  tags: openvpn-download

- name: Extract client credentials
  unarchive:
    src: "{{ openvpn_download_dir }}/{{ item }}.zip"
    dest: "{{ openvpn_download_dir }}"
  loop: "{{ openvpn_clients }}"
  become: false
  when:
    - openvpn_download_clients
    - openvpn_download_extract | bool
  delegate_to: localhost
  tags: openvpn-download
