- name: Ensure openvpn key dir has the right permission
  file:
    path: "{{ openvpn_key_dir }}"
    state: directory
    mode: 0o700
    owner: "{{ openvpn_user }}"

#- name: Check if crl.pem exists
#  stat:
#    path: "{{ openvpn_keydir }}/crl.pem"
#  register: crl_pem_file

- name: Configure server
  template:
    src: server.conf.j2
    dest: "{{ openvpn_etcdir }}/server.conf"
  notify: openvpn restart

# Needed by both tls-authentication tasks and client-configuration tasks. Placed
# here to avoid repeating it twice in both places where the tls and
# client-config tasks are located.
- name: Create client configuration directory
  file:
    path: "{{ openvpn_etcdir }}/ovpns"
    state: directory

# TODO: Move to tweaks?
- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable masquarade
  iptables:
    chain: POSTROUTING
    jump: MASQUERADE
    out_interface: "{{ openvpn_output_dev }}"
    table: nat
