---
- name: Does not converge
  hosts: all
  tasks:
    - block:
        - name: "Include openvpn"
          include_role:
            name: "openvpn"
          register: expected_failure
        - name: "Check execution failed"
          fail:
            msg: "Execution should stop before this task"
          register: should_not_run
      rescue:
        - name: Check that role shut itself down.
          assert:
            that:
              - expected_failure is defined
              - should_not_run is not defined
